import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import Navbar from '../components/Navbar'
import Offers from '../components/Offers'
import Plan from '../components/Plan'
import Rooms from '../components/Rooms'
import ImageSlider from '../components/ImageSlider'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <Navbar />
          <Hero />
          <Offers />
          <Plan />
          <Rooms />
          <ImageSlider />
          <Footer />
        </div>
      </main>
    </>
  )
}
